name: Automasi Testing sebelum merge

on:
  pull_request:
    branches: 
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          npm install -g htmlhint stylelint

      - name: Periksa HTML
        run: htmlhint "**/*.html"

      - name: Periksa CSS
        run: stylelint "**/*.css" --allow-empty-input
